version: '3.1'

services:

  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=news_api
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/databases/mysql:/var/lib/mysql